---
baseURL: https://www.billsingh.me
languageCode: en-us
title: Dr. Bill Singh, PHD
pygmentsstyle: monokai
metaDataFormat: yaml
module:
  imports:
  - path: github.com/forestryio/hugo-theme-novela
paginate: "6"
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
